services:
  db:
    image: mysql:8.0
    container_name: medisync-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: medisync-redis
    ports:
      - "6379:6379"

volumes:
  db-data: